var animations = [
  [ 
    {
        id: '#i01',
        duration: 250,
        delayBefore: 250,
        delayAfter: 0,
        easing: 'easeOutCubic',
        animations: {opacity: 1, left:0, top:0},   
    },
    {
        id: '#i02',
        duration: 750,
        delayBefore: 350,
        delayAfter: 0,
        easing: 'easeOutCubic',
        animations: {opacity: 1, left:0, top:0,scale: [5, 1]},   
    },
    {
        id: '#i03',
        duration: 750,
        delayBefore: 550,
        delayAfter: 0,
        easing: 'easeOutCubic',
        animations: {opacity: 1, left:0, top:0,},   
    },
    {
        id: '#i03-1',
        duration: 750,
        delayBefore: 650,
        delayAfter: 0,
        easing: 'easeOutCubic',
        animations: {opacity: 1, left:0, top:0},   
    },
    {
        id: '#i04',
        duration: 750,
        delayBefore: 750,
        delayAfter: 0,
        easing: 'easeOutCubic',
        animations: {opacity: 1, left:0, top:0},   
    },
    {
        id: '#i04-1',
        duration: 750,
        delayBefore: 850,
        delayAfter: 0,
        easing: 'easeOutCubic',
        animations: {opacity: 1, left:0, top:0},   
    },
    {
        id: '#i05',
        duration: 750,
        delayBefore: 1050,
        delayAfter: 0,
        easing: 'easeOutCubic',
        animations: {opacity: 1, left:0, top:0},   
    },
    {
        id: '#i05-1',
        duration: 750,
        delayBefore: 1150,
        delayAfter: 0,
        easing: 'easeOutCubic',
        animations: {opacity: 1, left:0, top:0},   
    },
    {
        id: '#i06',
        duration: 750,
        delayBefore: 1350,
        delayAfter: 0,
        easing: 'easeOutCubic',
        animations: {opacity: 1, left:0, top:0},   
    },
  ],
 ]
 new WAnimation(animations, {
     loop: false,
     clearAfterEnd: false,
   }).startAnimation();      