var animations = [
  [
    {
      id: "#i02",
      duration: 750,
      delayBefore: 150,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i03",
      duration: 750,
      delayBefore: 250,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i04",
      duration: 750,
      delayBefore: 350,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i01",
      duration: 750,
      delayBefore: 550,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i05",
      duration: 750,
      delayBefore: 650,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i06",
      duration: 750,
      delayBefore: 750,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i07",
      duration: 750,
      delayBefore: 750,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i08",
      duration: 750,
      delayBefore: 850,
      delayAfter: 3000,
      easing: "easeOutCubic",
      animations: { opacity: 1, top: 0, left: 0 },
    },
  ],
  [
    {
      id: "#i09",
      duration: 250,
      delayBefore: 150,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i10",
      duration: 750,
      delayBefore: 350,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i11",
      duration: 750,
      delayBefore: 450,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i12",
      duration: 750,
      delayBefore: 550,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i13",
      duration: 450,
      delayBefore: 650,
      delayAfter: 0,
      easing: "ease-in",
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i13-1",
      duration: 450,
      delayBefore: 750,
      delayAfter: 0,
      easing: "ease-in",
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i13-2",
      duration: 450,
      delayBefore: 850,
      delayAfter: 0,
      easing: "ease-in",
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i13-3",
      duration: 450,
      delayBefore: 950,
      delayAfter: 0,
      easing: "ease-in",
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i13-4",
      duration: 450,
      delayBefore: 1050,
      delayAfter: 0,
      easing: "ease-in",
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i13-5",
      duration: 450,
      delayBefore: 1150,
      delayAfter: 0,
      easing: "ease-in",
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i14",
      duration: 450,
      delayBefore: 1250,
      delayAfter: 3500,
      easing: "easeOutCubic",
      animations: { opacity: 1, top: 0, left: 0 },
    },
  ],
  [
    {
      id: "#i13",
      duration: 250,
      delayBefore: 0,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 0, top: 0, left: 0 },
    },
    {
      id: "#i13-1",
      duration: 250,
      delayBefore: 0,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 0, top: 0, left: 0 },
    },
    {
      id: "#i13-2",
      duration: 250,
      delayBefore: 0,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 0, top: 0, left: 0 },
    },
    {
      id: "#i13-3",
      duration: 250,
      delayBefore: 0,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 0, top: 0, left: 0 },
    },
    {
      id: "#i13-4",
      duration: 250,
      delayBefore: 0,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 0, top: 0, left: 0 },
    },
    {
      id: "#i13-5",
      duration: 250,
      delayBefore: 0,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 0, top: 0, left: 0 },
    },
    {
      id: "#i14",
      duration: 250,
      delayBefore: 0,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 0, top: 0, left: 0 },
    },
    {
      id: "#i10",
      duration: 250,
      delayBefore: 100,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 0, top: "-10%", left: 0 },
    },
    {
      id: "#i11",
      duration: 250,
      delayBefore: 200,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 0, top: "-10%", left: 0 },
    },
    {
      id: "#i12",
      duration: 250,
      delayBefore: 300,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 0, top: "10%", left: 0 },
    },
  ],
  [
    {
      id: "#i15",
      duration: 750,
      delayBefore: 150,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i16",
      duration: 750,
      delayBefore: 250,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i17",
      duration: 750,
      delayBefore: 450,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i18",
      duration: 450,
      delayBefore: 550,
      delayAfter: 0,
      easing: "ease-in",
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i18-1",
      duration: 450,
      delayBefore: 650,
      delayAfter: 0,
      easing: "ease-in",
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i18-2",
      duration: 450,
      delayBefore: 750,
      delayAfter: 0,
      easing: "ease-in",
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i18-3",
      duration: 450,
      delayBefore: 850,
      delayAfter: 0,
      easing: "ease-in",
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i18-4",
      duration: 450,
      delayBefore: 950,
      delayAfter: 0,
      easing: "ease-in",
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i18-5",
      duration: 450,
      delayBefore: 1050,
      delayAfter: 4000,
      easing: "ease-in",
      animations: { opacity: 1, top: 0, left: 0 },
    },
  ],
  [
    {
      id: "#i19",
      duration: 250,
      delayBefore: 0,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i20",
      duration: 750,
      delayBefore: 150,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i21",
      duration: 750,
      delayBefore: 250,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i22",
      duration: 750,
      delayBefore: 350,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i23",
      duration: 750,
      delayBefore: 450,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i24",
      duration: 450,
      delayBefore: 550,
      delayAfter: 0,
      easing: "ease-in",
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i25",
      duration: 450,
      delayBefore: 650,
      delayAfter: 3000,
      easing: "ease-in",
      animations: { opacity: 1, top: 0, left: 0 },
    },
  ],
];
new WAnimation(animations, {
  loop: true,
  clearAfterEnd: false,
}).startAnimation();
