var animations = [
  [
    {
      id: "#i01",
      duration: 250,
      delayBefore: 150,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i02",
      duration: 650,
      delayBefore: 150,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i03",
      duration: 650,
      delayBefore: 250,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i04",
      duration: 750,
      delayBefore: 350,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i05",
      duration: 750,
      delayBefore: 550,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i06",
      duration: 450,
      delayBefore: 650,
      delayAfter: 0,
      easing: "ease-in",
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i06-1",
      duration: 450,
      delayBefore: 750,
      delayAfter: 0,
      easing: "ease-in",
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i06-2",
      duration: 450,
      delayBefore: 850,
      delayAfter: 0,
      easing: "ease-in",
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i06-3",
      duration: 450,
      delayBefore: 950,
      delayAfter: 0,
      easing: "ease-in",
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i06-4",
      duration: 450,
      delayBefore: 1050,
      delayAfter: 3500,
      easing: "ease-in",
      animations: { opacity: 1, top: 0, left: 0 },
    },
  ],
  [
    {
      id: "#i07",
      duration: 250,
      delayBefore: 150,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i08",
      duration: 650,
      delayBefore: 350,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i09",
      duration: 750,
      delayBefore: 550,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i10",
      duration: 450,
      delayBefore: 650,
      delayAfter: 0,
      easing: "ease-in",
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i10-1",
      duration: 450,
      delayBefore: 750,
      delayAfter: 0,
      easing: "ease-in",
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i10-2",
      duration: 450,
      delayBefore: 850,
      delayAfter: 0,
      easing: "ease-in",
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i10-3",
      duration: 450,
      delayBefore: 950,
      delayAfter: 0,
      easing: "ease-in",
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i10-4",
      duration: 450,
      delayBefore: 1050,
      delayAfter: 4000,
      easing: "ease-in",
      animations: { opacity: 1, top: 0, left: 0 },
    },
  ],
  [
    {
      id: "#i11",
      duration: 250,
      delayBefore: 150,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i12",
      duration: 650,
      delayBefore: 350,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i13",
      duration: 750,
      delayBefore: 550,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i14",
      duration: 450,
      delayBefore: 650,
      delayAfter: 0,
      easing: "ease-in",
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i14-1",
      duration: 450,
      delayBefore: 750,
      delayAfter: 0,
      easing: "ease-in",
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i14-2",
      duration: 450,
      delayBefore: 850,
      delayAfter: 0,
      easing: "ease-in",
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i14-3",
      duration: 450,
      delayBefore: 950,
      delayAfter: 0,
      easing: "ease-in",
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i14-4",
      duration: 450,
      delayBefore: 1050,
      delayAfter: 4000,
      easing: "ease-in",
      animations: { opacity: 1, top: 0, left: 0 },
    },
  ],
  [
    {
      id: "#i15",
      duration: 250,
      delayBefore: 150,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i16",
      duration: 650,
      delayBefore: 350,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i17",
      duration: 650,
      delayBefore: 450,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i18",
      duration: 650,
      delayBefore: 550,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i19",
      duration: 750,
      delayBefore: 750,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i20",
      duration: 750,
      delayBefore: 850,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i21",
      duration: 750,
      delayBefore: 950,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i22",
      duration: 750,
      delayBefore: 1050,
      delayAfter: 0,
      easing: "easeOutCubic",
      animations: { opacity: 1, top: 0, left: 0 },
    },
    {
      id: "#i23",
      duration: 750,
      delayBefore: 1150,
      delayAfter: 3000,
      easing: "easeOutCubic",
      animations: { opacity: 1, top: 0, left: 0 },
    },
  ],
];
new WAnimation(animations, {
  loop: true,
  clearAfterEnd: false,
}).startAnimation();
